version: "3"
services:
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_username
      MONGO_INITDB_ROOT_PASSWORD: your_password
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db
    networks:
      - mongodb_network
networks:
  mongodb_network:
